[package]
name = "wakuchin_cli"
version = "0.1.0"
authors = ["P2P-Develop"]
default-run = "wakuchin"
edition = "2021"
license = "MIT"
repository = "https://github.com/P2P-Develop/wakuchin-rs"
description = "A next generation wakuchin researcher software written in Rust"

[[bin]]
name = "wakuchin"
path = "src/main.rs"

[build-dependencies]
wakuchin_core = { version = "0.1.0", path = "../core" }

[dependencies]
wakuchin_core = { version = "0.1.0", path = "../core" }

regex = "1"
tokio = { version = "=1.20", features = ["full"] }
