[package]
name = "wakuchin"
version = "0.2.0"
authors = ["P2P-Develop"]
categories = [ "science", "text-processing" ]
keywords = [ "text" ]
edition = "2021"
license-file = "../LICENSE"
repository = "https://github.com/P2P-Develop/wakuchin-rs"
description = "A next generation wakuchin researcher software written in Rust"
readme = "README.md"

[features]
chacha = []

[lib]
path = "src/lib.rs"

[dev-dependencies]
criterion = { version = "0.3", features = ["async_tokio"] }

[dependencies]
anyhow = "1.0"
crossbeam-channel = "0.5"
dashmap = "5.3"
divide_range = "0.1"
flume = "0.10"
iter-chunks = "0.1"
itertools = "0.10"
nanorand = "0.7"
num_cpus = "1.13"
regex = "1.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
smooth = "0.1"
thiserror = "1.0"
tokio = { version = "=1.20", features = ["sync", "time"] }

[[bench]]
name = "bench_core"
harness = false
