[package]
name = "wakuchin"
version = "0.1.0"
authors = ["P2P-Develop"]
category = "science"
keywords = [ "text" ]
edition = "2021"
license-file = "../LICENSE"
repository = "https://github.com/P2P-Develop/wakuchin-rs"
description = "A next generation wakuchin researcher software written in Rust"
readme = "../README.md"

exclude = [ "README.md" ]

[lib]
path = "src/lib.rs"

[dev-dependencies]
criterion = "0.3"

[dependencies]
rand = "0.8"
rayon = "1.5"
regex = "1.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[[bench]]
name = "bench_core"
harness = false
